version: '3.3'
services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  backend:
    container_name: foodgram-back
    build: ../backend/
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
      - redoc:/app/api/docs
  nginx:
    container_name: foodgram-proxy
    build: ../nginx/
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - redoc:/usr/share/nginx/html/api/docs/
      - static_volume:/static
      - media_volume:/media

volumes:
  static_volume:
  media_volume:
  pg_data:
  redoc:
