# Generated by Django 5.2.1 on 2025-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_follow_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
