# Generated by Django 5.2.1 on 2025-05-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipes',
        ),
    ]
