# Generated by Django 5.2.1 on 2025-05-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_favorite_options_alter_shoppingcart_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='RecipeIngredient',
        ),
    ]
