# Generated by Django 5.2.1 on 2025-05-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_rename_ingredientrecipe_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                help_text='Добавьте изображение рецепта',
                upload_to='recipes/',
                verbose_name='Картинка',
            ),
        ),
    ]
