# Generated by Django 5.2.1 on 2025-05-21 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_shortlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='short_link', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Короткая ссылка рецепта',
            },
        ),
        migrations.DeleteModel(
            name='ShortLink',
        ),
    ]
