# Generated by Django 5.2.1 on 2025-05-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_recipeshortlink_delete_shortlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeshortlink',
            name='created_at',
        ),
    ]
