# Generated by Django 5.2.1 on 2025-05-31 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_alter_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите время приготовления рецепта в минутах",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Минимальное время приготовления 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        32000, "Максимальное время приготовления 32000"
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
    ]
